### ISSUE TITLE
Change IBM OMR to Eclipse OMR in Python core GC sprint notes

### ISSUE THREAD

**Issue by nanjekyejoannah** [vstinner/faster_cpython#13]
Quoting ping from a reader of the notes

``
For the record, OMR should never be called "IBM OMR" ... OMR is an Eclipse Foundation project which means OMR is "owned" by the Eclipse Foundation. It should be described as "Eclipse OMR".
 
Calling it "IBM OMR" risks legal action from the Eclipse Foundation (but usually starts with a request to change it).

``
Just a wording mistake.

**Comment by nanjekyejoannah** [comment]
Fixed I guess.

**Comment by vstinner** [comment]
Fixed by https://github.com/vstinner/faster_cpython/commit/69af41e986dfd8d718454a05becafd276ce64b72
