### ISSUE TITLE
Synergy with python compiler workshop/efforts

### ISSUE THREAD

**Issue by datnamer** [vstinner/faster_cpython#3]
@njsmith Is holding a python compiler workshop at scipy that is meant to facilitate discussion among various python speedup efforts. (can't find link currently) 

Some of the ideas thrown around included opt in restricted semantics or type annotations so that modules can be JIT compiled by things like numba without having to be rewritten.

This line of investigation seems to dovetail quite nicely with some of the ideas presented in your peps like Pure functions, function guards, dictionary guards etc. Perhaps it would be worth investigating cooperation?

CC: @seibert and @pwang who might be interested

**Comment by haypo** [comment]
> Perhaps it would be worth investigating cooperation?

Sure. What is your plan? Do you want to enhance the future CPython 3.6?
